openapi: 3.0.0
info:
  title: The Earth Observatory Natural Event Tracker ([EONET](https://eonet.sci.gsfc.nasa.gov/what-is-eonet))
  version: 3.0.0
servers:
  - url: https://eonet.sci.gsfc.nasa.gov/api/v3
  - url: http://eonet.sci.gsfc.nasa.gov/api/v3
paths:
  /categories/{categoryId}:
    get:
      tags:
      - categories
      summary: Categories are the types of events by which individual events are cataloged
      description: Returns a single category
      operationId: getCategoryById
      parameters:
      - name: categoryId
        in: path
        description: ID of category to return
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Category not found
          content: {}
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
