# coding: utf-8

"""
    The Earth Observatory Natural Event Tracker ([EONET](https://eonet.sci.gsfc.nasa.gov/what-is-eonet))

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CategoryResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'description': 'str',
        'link': 'str',
        'events': 'list[OneOfCategoryResponseEventsItems]'
    }

    attribute_map = {
        'title': 'title',
        'description': 'description',
        'link': 'link',
        'events': 'events'
    }

    def __init__(self, title=None, description=None, link=None, events=None):  # noqa: E501
        """CategoryResponse - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._description = None
        self._link = None
        self._events = None
        self.discriminator = None
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        if link is not None:
            self.link = link
        if events is not None:
            self.events = events

    @property
    def title(self):
        """Gets the title of this CategoryResponse.  # noqa: E501


        :return: The title of this CategoryResponse.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CategoryResponse.


        :param title: The title of this CategoryResponse.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this CategoryResponse.  # noqa: E501


        :return: The description of this CategoryResponse.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CategoryResponse.


        :param description: The description of this CategoryResponse.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def link(self):
        """Gets the link of this CategoryResponse.  # noqa: E501


        :return: The link of this CategoryResponse.  # noqa: E501
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this CategoryResponse.


        :param link: The link of this CategoryResponse.  # noqa: E501
        :type: str
        """

        self._link = link

    @property
    def events(self):
        """Gets the events of this CategoryResponse.  # noqa: E501

        An array of events.  # noqa: E501

        :return: The events of this CategoryResponse.  # noqa: E501
        :rtype: list[OneOfCategoryResponseEventsItems]
        """
        return self._events

    @events.setter
    def events(self, events):
        """Sets the events of this CategoryResponse.

        An array of events.  # noqa: E501

        :param events: The events of this CategoryResponse.  # noqa: E501
        :type: list[OneOfCategoryResponseEventsItems]
        """

        self._events = events

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CategoryResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CategoryResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
